// packages/ui-react/src/page-fragment/src/PageFragment.tsx

import React from 'react';

import type { MComponent, MContainer, MPageFragment } from '@tmagic/schema';

import useApp from '../../useApp';
interface PageFragmentProps {
  config: MPageFragment;
}

const PageFragment: React.FC<PageFragmentProps> = ({ config }) => {
  const { app } = useApp({
    config,
    methods: {},
  });

  if (!app) return null;

  return (
    <div
      id={`${config.id || ''}`}
      className={`magic-ui-page-fragment magic-ui-container magic-layout-${config.layout}${
        config.className ? ` ${config.className}` : ''
      }`}
      style={app.transformStyle(config.style || {})}
    >
      {config.items?.map((item: MComponent | MContainer) => {
        const MagicUiComp = app.resolveComponent(item.type || 'container');

        if (!MagicUiComp) return null;

        if (item.visible === false) return null;
        if (item.condResult === false) return null;

        return (
          <MagicUiComp
            id={`${item.id || ''}`}
            key={item.id}
            config={item}
            className={`magic-ui-component${config.className ? ` ${config.className}` : ''}`}
            style={app.transformStyle(item.style || {})}
          ></MagicUiComp>
        );
      })}
    </div>
  );
};

PageFragment.displayName = 'magic-ui-page-fragment';

export default PageFragment;

// packages/ui/src/page-fragment/src/PageFragment.vue
<template>
  <div
    :id="`${config.id || ''}`"
    :class="`magic-ui-page-fragment magic-ui-container magic-layout-${config.layout}${
      config.className ? ` ${config.className}` : ''
    }`"
    :style="style"
  >
    <slot></slot>
    <MComponent v-for="item in config.items" :key="item.id" :config="item"></MComponent>
  </div>
</template>

<script lang="ts" setup>
import { computed, inject } from 'vue';

import Core from '@tmagic/core';
import type { MPageFragment } from '@tmagic/schema';

import MComponent from '../../Component.vue';
import useApp from '../../useApp';

const props = withDefaults(
  defineProps<{
    config: MPageFragment;
    model?: any;
  }>(),
  {
    model: () => ({}),
  },
);

const app: Core | undefined = inject('app');

const style = computed(() => app?.transformStyle(props.config.style || {}));

useApp({
  config: props.config,
  methods: {},
});
</script>
