// react-components/page-fragment/src/PageFragment.tsx
import React from 'react';

import { useApp } from '@tmagic/react-runtime-help';
import type { MPageFragment } from '@tmagic/schema';

interface PageFragmentProps {
  config: MPageFragment;
}

const PageFragment: React.FC<PageFragmentProps> = ({ config }) => {
  const { app } = useApp({
    config,
    methods: {},
  });

  if (!app) return null;

  const MagicUiComp = app.resolveComponent('container');
  const classNames = ['magic-ui-page-fragment'];
  if (config.className) {
    classNames.push(config.className);
  }

  return <MagicUiComp config={config} id={config.id} className={classNames.join(' ')}></MagicUiComp>;
};

PageFragment.displayName = 'magic-ui-page-fragment';

export default PageFragment;

// vue-components/page-fragment/src/PageFragment.vue
<template>
  <magic-ui-container
    class="magic-ui-page-fragment"
    :data-tmagic-id="config.id"
    :config="config"
    :style="app?.transformStyle(config.style || {})"
  ></magic-ui-container>
</template>

<script lang="ts">
import { defineComponent, type PropType } from 'vue-demi';

import type { MPageFragment } from '@tmagic/schema';
import { useApp } from '@tmagic/vue-runtime-help';

export default defineComponent({
  props: {
    config: {
      type: Object as PropType<MPageFragment>,
      required: true,
    },
    model: {
      type: Object,
      default: () => ({}),
    },
  },

  setup(props) {
    const { app } = useApp({
      config: props.config,
      methods: {},
    });

    return {
      app,
    };
  },
});
</script>
