// react-components/iterator-container/src/IteratorContainer.tsx
import React from 'react';

import type { IteratorContainer as TMagicIteratorContainer } from '@tmagic/core';
import { useApp } from '@tmagic/react-runtime-help';
import type { Id, MIteratorContainer, MNode } from '@tmagic/schema';

interface IteratorContainerSchema extends Omit<MIteratorContainer, 'id'> {
  id?: Id;
  type?: 'iterator-container';
}

interface IteratorContainerProps {
  config: IteratorContainerSchema;
  className: string;
  style: Record<string, any>;
  id: string;
  containerIndex: number;
  iteratorIndex: number[];
  iteratorContainerId: Id[];
}

interface IteratorItemSchema {
  items: MNode[];
  condResult: boolean;
  style: {
    [key: string]: any;
  };
}

const IteratorContainer: React.FC<IteratorContainerProps> = ({
  config,
  id,
  style,
  className,
  containerIndex,
  iteratorIndex,
  iteratorContainerId,
}) => {
  const { app } = useApp({ config, iteratorIndex, iteratorContainerId });

  let { iteratorData = [] } = config;
  const { itemConfig, dsField, items } = config;

  if (!Array.isArray(iteratorData)) {
    iteratorData = [];
  }

  if (app?.platform === 'editor' && !iteratorData.length) {
    iteratorData.push({});
  }

  const MagicUiComp = app?.resolveComponent('container');

  const iteratorContainerNode = app?.getNode<TMagicIteratorContainer>(
    id || config.id || '',
    iteratorContainerId,
    iteratorIndex,
  );

  iteratorContainerNode?.resetNodes();

  const configs: IteratorItemSchema[] = iteratorData.map((itemData: any, index: number) => {
    const condResult =
      app?.platform !== 'editor'
        ? app?.dataSourceManager?.compliedIteratorItemConds(itemData, itemConfig, dsField) ?? true
        : true;

    const newItems = app?.dataSourceManager?.compliedIteratorItems(itemData, items, dsField) ?? items;

    iteratorContainerNode?.setNodes(config.items, index);

    return {
      items: newItems,
      condResult,
      style: {
        position: 'relative',
        left: 0,
        top: 0,
        ...itemConfig.style,
      },
    };
  });

  return (
    <div
      className={className}
      style={style}
      data-tmagic-id={`${id || config.id || ''}`}
      data-container-index={containerIndex}
      data-iterator-index={iteratorIndex}
      data-iterator-container-id={iteratorContainerId}
    >
      {configs.map((config: any, index: number) => (
        <MagicUiComp
          config={config}
          key={index}
          style={app?.transformStyle(config.style)}
          iteratorIndex={[...(iteratorIndex || []), index]}
          iteratorContainerId={[...(iteratorContainerId || []), config.id]}
        ></MagicUiComp>
      ))}
    </div>
  );
};

IteratorContainer.displayName = 'magic-ui-iterator-container';

export default IteratorContainer;

// packages/ui/src/iterator-container/src/IteratorContainer.vue
<template>
  <div
    class="magic-ui-iterator-container"
    :data-iterator-index="dataIteratorIndex"
    :data-iterator-container-id="dataIteratorContainerId"
  >
    <Container
      v-for="(item, index) in configs"
      :iterator-index="[...(dataIteratorIndex || []), index]"
      :iterator-container-id="[...(dataIteratorContainerId || []), config.id]"
      :key="index"
      :config="item"
    ></Container>
  </div>
</template>

<script lang="ts" setup>
import { computed } from 'vue';

import { type Id, type MIteratorContainer, NodeType, TMagicIteratorContainer } from '@tmagic/schema';
import { useApp } from '@tmagic/vue-runtime-help';

import Container from '../../container';

const props = withDefaults(
  defineProps<{
    config: MIteratorContainer;
    model?: any;
    dataIteratorIndex?: number[];
    dataIteratorContainerId?: Id[];
  }>(),
  {
    model: () => ({}),
  },
);

const { app, node } = useApp({
  config: props.config,
  iteratorContainerId: props.dataIteratorContainerId,
  iteratorIndex: props.dataIteratorIndex,
  methods: {},
});

const iteratorContainerNode = node as unknown as TMagicIteratorContainer;

const configs = computed(() => {
  let { iteratorData = [] } = props.config;
  const { id, itemConfig, dsField, items } = props.config;

  if (!Array.isArray(iteratorData)) {
    iteratorData = [];
  }

  if (app?.platform === 'editor' && !iteratorData.length) {
    iteratorData.push({});
  }

  iteratorContainerNode?.resetNodes();

  return iteratorData.map((itemData, index) => {
    const condResult =
      app?.platform !== 'editor'
        ? app?.dataSourceManager?.compliedIteratorItemConds(itemData, itemConfig, dsField) ?? true
        : true;

    const newItems =
      app?.dataSourceManager?.compliedIteratorItems(
        id,
        itemData,
        items,
        dsField,
        props.dataIteratorContainerId,
        props.dataIteratorIndex,
      ) ?? items;

    iteratorContainerNode?.setNodes(newItems, index);

    return {
      items: newItems,
      id: '',
      type: NodeType.CONTAINER,
      condResult,
      style: {
        ...itemConfig.style,
        position: 'relative',
        left: 0,
        top: 0,
      },
    };
  });
});
</script>
