// packages/ui-react/src/page-fragment-container/src/PageFragmentContainer.tsx

import React, { constructor, useEffect, useMemo, useState } from 'react';

import type { MComponent, MContainer, MNode, MPage, MPageFragment } from '@tmagic/schema';

import useApp from '../../useApp';
interface PageFragmentContainerProps {
  config: MComponent;
}

const PageFragmentContainer: React.FC<PageFragmentContainerProps> = ({ config }) => {
  const { app } = useApp({
    config,
    methods: {},
  });

  if (!app) return null;
  const MagicUiContainer = app.resolveComponent('container');
  let containerConfig = {}
  const fragment = app?.dsl?.items?.find((page) => page.id === config.pageFragmentId)
  if(fragment) {
    const { id, type, items, ...others } = fragment;
    const itemsWithoutId = items.map((item: MNode) => {
      const { id, ...otherConfig } = item;
      return otherConfig;
    });
    if (app?.platform === 'editor') {
      containerConfig ={
        ...others,
        items: itemsWithoutId,
      };
    }else {
      containerConfig = {
        ...others,
        items
      }
    }
  }

  return (
    <div
      id={`${config.id || ''}`}
      className="magic-ui-page-fragment-container"
      style={app.transformStyle(config.style || {})}
    >
      <MagicUiContainer
        config={containerConfig}
      ></MagicUiContainer>
    </div>
  );
};

PageFragmentContainer.displayName = 'magic-ui-page-fragment-container';

export default PageFragmentContainer;

// packages/ui-vue2/src/page-fragment-container/src/PageFragmentContainer.vue
<template>
  <div :id="`${config.id || ''}`" class="magic-ui-page-fragment-container">
    <magic-ui-container :config="containerConfig" :model="model"></magic-ui-container>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, PropType } from 'vue';

import { MComponent, MNode } from '@tmagic/schema';

import Container from '../../container';
import useApp from '../../useApp';

export default defineComponent({
  components: {
    'magic-ui-container': Container,
  },

  props: {
    config: {
      type: Object as PropType<MComponent>,
      default: () => ({}),
    },
  },

  setup(props) {
    const app = useApp(props);
    const fragment = computed(() => app?.dsl?.items?.find((page) => page.id === props.config.pageFragmentId));
    const containerConfig = computed(() => {
      if (!fragment.value) return { items: [] };
      const { id, type, items, ...others } = fragment.value;
      const itemsWithoutId = items.map((item: MNode) => {
        const { id, ...otherConfig } = item;
        return otherConfig;
      });
      if (app?.platform === 'editor') {
        return {
          ...others,
          items: itemsWithoutId,
        };
      }
      return {
        ...others,
        items,
      };
    });
    return {
      containerConfig,
    };
  },
});
</script>
<style scoped>
.in-editor .magic-ui-page-fragment-container {
  min-width: 100px;
  min-height: 100px;
}
</style>
