// packages/ui-vue2/src/page-fragment/src/PageFragment.vue
<template>
  <div
    :id="`${config.id || ''}`"
    :class="`magic-ui-page-fragment magic-ui-container magic-layout-${config.layout}${
      config.className ? ` ${config.className}` : ''
    }`"
    :style="style"
  >
    <slot></slot>
    <magic-ui-component v-for="item in config.items" :key="item.id" :config="item"></magic-ui-component>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, PropType } from 'vue';

import type { MPageFragment } from '@tmagic/schema';

import MComponent from '../../Component.vue';
import useApp from '../../useApp';

export default defineComponent({
  components: {
    'magic-ui-component': MComponent,
  },

  props: {
    config: {
      type: Object as PropType<MPageFragment>,
      default: () => ({}),
    },
  },

  setup(props) {
    const app = useApp(props);

    return {
      style: computed(() => app?.transformStyle(props.config.style || {})),
    };
  },
});
</script>

// packages/ui-react/src/page-fragment/src/PageFragment.tsx

import React from 'react';

import type { MComponent, MContainer, MPageFragment } from '@tmagic/schema';

import useApp from '../../useApp';
interface PageFragmentProps {
  config: MPageFragment;
}

const PageFragment: React.FC<PageFragmentProps> = ({ config }) => {
  const { app } = useApp({
    config,
    methods: {},
  });

  if (!app) return null;

  return (
    <div
      id={`${config.id || ''}`}
      className={`magic-ui-page-fragment magic-ui-container magic-layout-${config.layout}${
        config.className ? ` ${config.className}` : ''
      }`}
      style={app.transformStyle(config.style || {})}
    >
      {config.items?.map((item: MComponent | MContainer) => {
        const MagicUiComp = app.resolveComponent(item.type || 'container');

        if (!MagicUiComp) return null;

        if (item.visible === false) return null;
        if (item.condResult === false) return null;

        return (
          <MagicUiComp
            id={`${item.id || ''}`}
            key={item.id}
            config={item}
            className={`magic-ui-component${config.className ? ` ${config.className}` : ''}`}
            style={app.transformStyle(item.style || {})}
          ></MagicUiComp>
        );
      })}
    </div>
  );
};

PageFragment.displayName = 'magic-ui-page-fragment';

export default PageFragment;
