// packages/ui/src/page-fragment/src/PageFragment.vue
<template>
  <MContainer class="magic-ui-page-fragment" :config="config"></MContainer>
</template>

<script lang="ts" setup>
import type { MPageFragment } from '@tmagic/schema';
import { useApp } from '@tmagic/vue-runtime-help';

import MContainer from '../../container';

const props = withDefaults(
  defineProps<{
    config: MPageFragment;
    model?: any;
  }>(),
  {
    model: () => ({}),
  },
);

useApp({
  config: props.config,
  methods: {},
});
</script>

// react-components/page-fragment/src/PageFragment.tsx
import React from 'react';

import { useApp } from '@tmagic/react-runtime-help';
import type { MPageFragment } from '@tmagic/schema';

interface PageFragmentProps {
  config: MPageFragment;
}

const PageFragment: React.FC<PageFragmentProps> = ({ config }) => {
  const { app } = useApp({
    config,
    methods: {},
  });

  if (!app) return null;

  const MagicUiComp = app.resolveComponent('container');
  const classNames = ['magic-ui-page-fragment'];
  if (config.className) {
    classNames.push(config.className);
  }

  return <MagicUiComp config={config} id={config.id} className={classNames.join(' ')}></MagicUiComp>;
};

PageFragment.displayName = 'magic-ui-page-fragment';

export default PageFragment;
